[package]
name = "ui"
version = "0.1.0"
description = "UI components for Crabfin"
edition.workspace = true
license.workspace = true
repository.workspace = true
authors.workspace = true

[lib]
path = "src/ui.rs"

[dependencies]
credentials.workspace = true
gpui.workspace = true
jellyfin.workspace = true
settings.workspace = true
theme.workspace = true
tokio = { workspace = true, features = ["rt-multi-thread"] }
tracing.workspace = true
unicode-segmentation.workspace = true
uuid.workspace = true

dirs.workspace = true
image.workspace = true
lru.workspace = true
reqwest.workspace = true

