[package]
name = "jellyfin"
version = "0.1.0"
description = "Jellyfin API client SDK"
edition.workspace = true
license.workspace = true
repository.workspace = true
authors.workspace = true

[lib]
path = "src/jellyfin.rs"

[dependencies]
reqwest.workspace = true
serde.workspace = true
serde_json.workspace = true
tokio.workspace = true
thiserror.workspace = true
anyhow.workspace = true
uuid = { version = "1", features = ["v4"] }
hostname = "0.4"
